# Generated by Django 5.1.2 on 2024-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('no_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('utilities', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('property_zillow_link', models.URLField()),
                ('property_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Error', 'Error')], default='Pending', max_length=20)),
                ('yearly_rent_cost_util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_projected_revenue', models.IntegerField(blank=True, null=True)),
                ('monthly_estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_id', models.IntegerField()),
            ],
        ),
    ]
