# Generated by Django 5.1.2 on 2024-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rentalproperty_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalproperty',
            name='user',
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
