# Generated by Django 5.1.2 on 2026-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_rentalproperty_user_rentalproperty_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalproperty',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'rental properties'},
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='batch_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rentalproperty',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rentalproperty',
            index=models.Index(fields=['user_id', '-created_at'], name='rental_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalproperty',
            index=models.Index(fields=['property_status', 'monthly_estimated_profit'], name='rental_status_profit_idx'),
        ),
    ]
