# Generated by Django 5.1.2 on 2024-10-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_alter_lease_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
