# Generated by Django 5.1.2 on 2024-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20),
        ),
    ]
