# Generated by Django 5.1.2 on 2024-11-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0004_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Processing', 'Processing')], default='Processing', max_length=20),
        ),
    ]
