# Generated by Django 5.1.2 on 2024-11-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_alter_document_status_alter_lease_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
    ]
