# Generated by Django 5.1.2 on 2024-11-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0006_alter_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gpt_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
