# Generated by Django 5.1.2 on 2024-11-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0007_document_gpt_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
