# Generated by Django 5.1.2 on 2024-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0008_document_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
