# Generated by Django 5.1.2 on 2026-09-22 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0009_document_file_url_alter_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['lease', '-version'], name='document_lease_version_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['user', '-created_at'], name='lease_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='lease_status_idx'),
        ),
    ]
