# Generated by Django 5.1.2 on 2024-11-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('allowed', 'STR Allowed'), ('not_allowed', 'STR Not Allowed'), ('restricted', 'STR Allowed with Restrictions'), ('pending', 'STR Pending Approval')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gpt_response', models.JSONField(blank=True, null=True)),
                ('chat_history', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
