# Generated by Django 5.1.2 on 2024-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='status',
            field=models.CharField(choices=[('allowed', 'STR Allowed'), ('not_allowed', 'STR Not Allowed'), ('restricted', 'STR Allowed with Restrictions'), ('pending', 'STR Pending Approval')], default='pending', max_length=50),
        ),
    ]
