# Generated by Django 5.1.2 on 2024-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_alter_regulations_area_alter_regulations_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='status',
            field=models.CharField(choices=[('STR Allowed', 'STR Allowed'), ('STR Not Allowed', 'STR Not Allowed'), ('STR Allowed with Restrictions', 'STR Allowed with Restrictions'), ('STR Pending Approval', 'STR Pending Approval')], default='pending', max_length=50),
        ),
    ]
