# Generated by Django 5.1.2 on 2024-11-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_alter_regulations_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulations',
            old_name='address',
            new_name='search',
        ),
        migrations.RemoveField(
            model_name='regulations',
            name='area',
        ),
        migrations.RemoveField(
            model_name='regulations',
            name='city',
        ),
    ]
