# Generated by Django 5.1.2 on 2026-09-22 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_rename_address_regulations_search_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulations',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'regulations'},
        ),
        migrations.AddField(
            model_name='regulations',
            name='analysis_state',
            field=models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='regulations',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='regulations',
            name='status',
            field=models.CharField(choices=[('STR Allowed', 'STR Allowed'), ('STR Not Allowed', 'STR Not Allowed'), ('STR Allowed with Restrictions', 'STR Allowed with Restrictions'), ('STR Pending Approval', 'STR Pending Approval'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='regulations',
            index=models.Index(fields=['user', '-created_at'], name='regulation_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='regulations',
            index=models.Index(fields=['status'], name='regulation_status_idx'),
        ),
    ]
