# Generated by Django 5.1.2 on 2024-10-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin User'), ('research', 'Research User'), ('coach', 'Coach User'), ('client', 'Client User')], default='Client', max_length=50),
        ),
    ]
