# Generated by Django 5.1.2 on 2024-10-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin User'), ('research', 'Research User'), ('coach', 'Coach User'), ('client', 'Client User'), ('general', 'General User')], default='client', max_length=50),
        ),
    ]
