# Generated by Django 5.1.2 on 2024-10-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin User'), ('research', 'Research User'), ('coach', 'Coach User'), ('client', 'Client User'), ('customer', 'Customer User')], default='customer', max_length=50),
        ),
    ]
