# Generated by Django 5.1.2 on 2024-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin User'), ('research', 'Research User'), ('coach', 'Coach User'), ('client', 'Client User'), ('customer', 'Customer User')], default='admin', max_length=50),
        ),
    ]
